### ISSUE TITLE
Beamer theme?

### ISSUE THREAD

**Issue by kir0ul** [cwkx/cwkx.github.io#3]
Hi,
Just curious, can I ask what is the Beamer theme or the class used to create these lectures: https://github.com/cwkx/cwkx.github.io/tree/master/data/teaching/dl-and-rl ? I really like this style! :slightly_smiling_face: 
Thanks in advance!

**Comment by cwkx** [comment]
Hi, 
It's a slight modification to: https://github.com/pvanberg/flux-beamer
Thanks

**Comment by kir0ul** [comment]
Thank you!
